
supabase_url = "https://mrnqxqzloowrokgggufr.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ybnF4cXpsb293cm9rZ2dndWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDM0MDYsImV4cCI6MjA2MjAxOTQwNn0.jnLdc31w8fVpA2SaunyGBd_HCdavHYlWZa4SVKYK0WA"

[n8n]
webhook_url = "https://davidmolad.app.n8n.cloud/webhook-test/26f4bd00-6fb2-45d4-9650-8b0c06f01c8f"